version: '3'

services:
  # Server / API - Node JS
  server:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"